version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis_nextcloud
    restart: always
    networks:
      - network_app
      - proxy

  nextcloud:
    image: nextcloud:latest
    restart: always
    container_name: nextcloud
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - proxy
      - network_app
    
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ=America/Argentina/Buenos_Aires
      - REDIS_HOST=redis
      - HOSTNAME_NEXTCLOUD


    labels:
      - traefik.enable=true
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      - traefik.http.routers.nextcloud.entrypoints=web
      - traefik.http.routers.nextcloud.rule=Host(`${HOSTNAME_NEXTCLOUD}`) # Your Domain Name goes here for the http rule
      - traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.nextcloud.middlewares=nextcloud-https-redirect #  This is a middleware to redirect to https
      - traefik.http.routers.nextcloud-secure.rule=Host(`${HOSTNAME_NEXTCLOUD}`) # Your Domain Name for the https rule 
      - traefik.http.routers.nextcloud-secure.entrypoints=websecure  #  Defining entrypoint for https,
      - traefik.http.routers.nextcloud-secure.tls=true
      - traefik.http.routers.nextcloud-secure.tls.certresolver=letsencrypt # Defining certsresolvers for https
    
    depends_on:
      - redis

volumes:
  nextcloud_data:

networks:
  proxy:
    external: true
  network_app:
    external: true
    