version: '3.8'

services:
  nginx:
    image: nginx:alpine
  
  labels:
    - 'traefik.http.routers.nginx.rule=Host(`proxy.yubi.com.ar`)'
  networks:
    - proxy

networks:
  proxy:
    driver: bridge