version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:alpine
    restart: always
    container_name: portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

    labels:
      - traefik.enable=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.routers.portainer.rule=Host(`${HOSTNAME_PORTAINER}`) # Your Domain Name goes here for the http rule
      - traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.portainer.middlewares=portainer-https-redirect #  This is a middleware to redirect to https
      - traefik.http.routers.portainer-secure.rule=Host(`${HOSTNAME_PORTAINER}`) # Your Domain Name for the https rule 
      - traefik.http.routers.portainer-secure.entrypoints=websecure  #  Defining entrypoint for https,
      - traefik.http.routers.portainer-secure.tls=true
      - traefik.http.routers.portainer-secure.tls.certresolver=letsencrypt # Defining certsresolvers for https
    networks:
      - proxy

volumes:
  portainer_data:
    
networks:
  proxy:
    external: true
